[EN-6393] feat(form-inscription): add mail ts
ReseauEntourage/entourage-job-back pull request #101
Opened 2023-10-05 12:04 UTC by PaulEntourage

2023-10-09 09:48 UTC, emile-bex requested changes

2023-10-09 09:48 UTC, emile-bex commented on src/external-services/salesforce/salesforce.types.ts
> +  [HeardAbout.ORIENTATION]: 'Par mon travailleur social/Pôle emploi',
Cette option n'existe pas dans la liste des options du champ `Comment_vous_nous_avez_connu__c ` sur les _Prospect_

2023-10-09 09:48 UTC, emile-bex commented on src/external-services/salesforce/salesforce.types.ts
> +  [HeardAbout.ORIENTATION]: 'Par mon travailleur social/Pôle emploi',
https://entourage2--dev2loko.sandbox.lightning.force.com/lightning/setup/ObjectManager/Lead/FieldsAndRelationships/00N7Q000008zmfZ/view

2023-10-09 09:48 UTC, emile-bex commented on src/external-services/salesforce/salesforce.utils.ts
> +      TS_du_Candidat__c: tsPrescripteur,
C'est normal que ce champ c'est juste du texte, et pas une référence à un autre champ `Prospect` ou `Contact` ?

2023-10-10 08:06 UTC, PaulEntourage commented on src/external-services/salesforce/salesforce.utils.ts
> +      TS_du_Candidat__c: tsPrescripteur,
Oui :)

2023-10-16 12:20 UTC, emile-bex approved these changes

2023-10-17 09:12 UTC, merged