[EN-5108] feature: refonte membres - route bulk candidat user
ReseauEntourage/entourage-job-back pull request #13
Opened 2022-10-14 14:08 UTC by PaulEntourage

2022-10-14 14:19 UTC, emile-bex requested changes

2022-10-14 14:19 UTC, emile-bex commented on src/users/user-candidats.service.ts
> +        returning: true,
Il faut absolument mettre le paramètre `individualHooks: true,` à chaque update avec l'ORM. On se fait un point pour que je t'explique 😉

2022-11-03 11:15 UTC, PaulEntourage commented on tests/users/users.e2e-spec.ts
> +          expect(responseCoach.status).toBe(403);
T'as raison, je voulais factoriser du code parce que ca fait beaucoup de duplication. Mais il vaut mieux faire comme tu l'as dit.

2022-11-03 11:34 UTC, PaulEntourage commented on tests/users/user-candidats.helper.ts
> +  async findAllUserCandidatsById(UserIds: string[]): Promise<UserCandidat[]> {
Tu pourras checker les tests, j'ai commit ton proposition de modif, je crois que ca les fait planter :/

2022-11-03 11:39 UTC, emile-bex commented on tests/users/user-candidats.helper.ts
> +    return this.userCandidatsService.findAllById(UserIds);
```suggestion
    return this.userCandidatsService.findAllById(usersIds);
```

2022-11-08 09:24 UTC, emile-bex approved these changes

2022-11-08 09:25 UTC, merged