[EN-7320] Onboarding J1 email
ReseauEntourage/entourage-job-back pull request #198
Opened 2024-08-21 10:14 UTC by DDZBX

Un peu de refacto pour identifier facilement tous les emails d'onboarding

2024-08-21 15:09 UTC, guillobits requested changes

2024-08-21 15:09 UTC, guillobits commented on src/users-creation/users-creation.controller.ts
> +      );
C'est du fine tuning, mais vu qu'on a 4 processus qui pourrait (si j'ai bien compris) être en parallèles, on peut envisager d'utiliser un Primise.all ?

2024-08-21 15:14 UTC, DDZBX commented on src/users-creation/users-creation.controller.ts
> +      );
On pourrait oui
- l'envoie de message est en fait seulement une ecriture dans la base redis (presque instant)
- on fait pas vraiment d'action apres donc on s'en fout un peu s'il a fini ou pas 
- je trouve ca plus lisible que de faire un promise all

2024-08-22 11:10 UTC, guillobits approved these changes

2024-08-22 14:59 UTC, merged