Gestion du role Orienteur
ReseauEntourage/entourage-job-back pull request #217
Opened 2024-10-11 12:39 UTC by guillobits

2024-10-23 12:43 UTC, DDZBX commented on src/users/models/user.include.ts
> +      // },
Tu veux laisser les commentaires ?

2024-10-23 13:02 UTC, DDZBX requested changes
Pas tout testé manuellement parce qu'il va surement encore avoir des changements. 
J'ai l'impression que globalement ca simplifie quand meme des trucs de ne plus avoir les variantes externes des roles 
Une fois qu'on sera plus ou moins OK faudrait peut etre qu'on organise une session de testing en invitant quelques personnes pour etre sur que les fonctionnalités soient bonnes ? Qu'en penses tu ?

2024-10-23 13:02 UTC, DDZBX commented on tests/users/users.e2e-spec.ts
> -
Faudrait qu'on prévoie des cas de tests sur le referrer, j'ajoute a la liste des choses a discuter :)

2024-10-25 13:28 UTC, guillobits commented on tests/users/users.e2e-spec.ts
> -
Yes c'est sûr, après y'a tellement rien de sec pour l'instant que je pense que c'est pas encore le moment. 
Par contre on peut créer un ticket pour ça

2024-10-25 13:30 UTC, guillobits commented on src/users/users.types.ts
> +export const CandidateUserRoles: CandidateUserRole[] = [UserRoles.CANDIDATE];
J'ai même fait mieux. CandidateUserRole ne sert à rien en soit si il est seul, donc j'ai refacto partout

2024-11-07 14:19 UTC, DDZBX approved these changes
J'ai pas tout testé manuellement mais tes changements semblent good, j'imagine que les tests seront corrigés dans une autre PR ou dans la branche d'epic ?

2024-11-07 14:50 UTC, merged