migration
ReseauEntourage/entourage-job-back pull request #23
Opened 2022-11-22 17:06 UTC by PaulEntourage

2022-11-22 17:23 UTC, emile-bex requested changes

2022-11-22 17:23 UTC, emile-bex commented on src/db/migrations/20221122161833-create-opportunities-status-change.js
> +    return queryInterface.createTable('Opportunity_StatusChange', {
Plutôt `Opportunity_StatusChanges` pour le nom de la table (pour être ISO avec le nom des tables au pluriel 😉

2022-11-22 17:23 UTC, emile-bex commented on src/opportunities/models/opportunity_statusChange.ts
> +  Opportunity_UsersId: string;
```suggestion
  OpportunityUserId: string;
```

2022-11-22 17:23 UTC, emile-bex commented on src/db/migrations/20221122161833-create-opportunities-status-change.js
> +    await queryInterface.dropTable('Opportunity_StatusChange');
```suggestion
    await queryInterface.dropTable('Opportunity_StatusChanges');
```

2022-11-22 17:23 UTC, emile-bex commented on src/db/migrations/20221122161833-create-opportunities-status-change.js
> +    return queryInterface.createTable('Opportunity_StatusChange', {
```suggestion
    return queryInterface.createTable('Opportunity_StatusChanges', {
```

2022-11-22 17:23 UTC, emile-bex commented on src/opportunities/models/opportunity_statusChange.ts
> +export class Opportunity_statusChange extends Model {
```suggestion
export class OpportunityStatusChange extends Model {
```

2022-11-22 17:23 UTC, emile-bex commented on src/opportunities/models/opportunity_statusChange.ts
> +@Table({ tableName: 'Opportunity_StatusChange' })
```suggestion
@Table({ tableName: 'Opportunity_StatusChanges' })
```

2022-11-22 17:23 UTC, emile-bex commented on src/db/migrations/20221122161833-create-opportunities-status-change.js
> +      Opportunity_UsersId: {
On va plutôt mettre `OpportunityUserId` vu que c'est un seul `OpportunityUser` et il les underscores c'est que le nom des tables ;)

2022-11-22 17:23 UTC, emile-bex commented on src/db/migrations/20221122161833-create-opportunities-status-change.js
> +      Opportunity_UsersId: {
```suggestion
      OpportunityUserId: {
```

2022-11-23 16:26 UTC, emile-bex commented on src/opportunities/models/opportunity-user.model.ts
> +    const previousStatus = updatedOpportunityUser.previous().status;
Il me semble ici que tu peux faire plutôt `updatedOpportunityUser.previous('status')`

2022-11-23 16:26 UTC, emile-bex commented on src/opportunities/models/opportunity-user.model.ts
> +  @HasMany(() => OpportunityUserStatusChange, 'opportunityUserStatusChanges')
Je crois qu'il faut préciser le nom de la foreign key ici `OpportunityUserId` non ?

2022-11-24 09:43 UTC, PaulEntourage commented on src/db/migrations/20221122161833-create-opportunities-status-change.js
> +        })
Yes ok je corrige, je me suis planté, je pensais qu'un truc similaire avait été fait sur le même type d'association.

2022-11-24 09:48 UTC, PaulEntourage commented on src/db/migrations/20221122161833-create-opportunities-status-change.js
> +            type: Sequelize.INTEGER
yes ok

2022-11-24 09:50 UTC, PaulEntourage commented on src/opportunities/models/opportunity-user.model.ts
> +  @HasMany(() => OpportunityUserStatusChange, 'opportunityUserStatusChanges')
Oui y'as raison

2022-11-24 09:52 UTC, PaulEntourage commented on src/opportunities/models/opportunity-user.model.ts
> +  @HasMany(() => OpportunityUserStatusChange, 'opportunityUserStatusChanges')
Du coup ce sera OpportunityUserStatusChangeId, non?

2022-11-24 10:05 UTC, emile-bex commented on src/opportunities/models/opportunity-user.model.ts
> +  @HasMany(() => OpportunityUserStatusChange, 'opportunityUserStatusChanges')
Non justement en gros l'association va de `Opportunity_User_StatusChanges` vers `Opportunity_Users`. C'est `OpportunityUserStatusChangeId` qui à une foreign key `OpportunityUserId`. Dans Sequelize, quand tu déclares une relation `HasMany`, la foreign key que tu indiques c'est celle de l'autre table qui référence cette table.

2022-11-24 10:06 UTC, PaulEntourage commented on src/opportunities/models/opportunity-user.model.ts
> +  @HasMany(() => OpportunityUserStatusChange, 'opportunityUserStatusChanges')
Ok j'ai compris

2022-11-24 12:26 UTC, PaulEntourage commented on src/opportunities/models/opportunity-user.model.ts
> +  @BeforeUpdate
ok !

2022-11-24 12:26 UTC, PaulEntourage commented on src/opportunities/models/opportunity-user.model.ts
> +    const previousStatus = updatedOpportunityUser.previous().status;
Yes ca marche bien

2022-11-28 18:04 UTC, emile-bex approved these changes

2022-11-28 18:17 UTC, merged