[EN-5292]: contact relance entreprise
ReseauEntourage/entourage-job-back pull request #32
Opened 2023-02-03 10:45 UTC by PaulEntourage

2023-02-06 08:53 UTC, emile-bex requested changes

2023-02-06 08:53 UTC, emile-bex commented on src/mails/mails.service.ts
> +    })
Attention au `console.log` à supprimer ;)

2023-02-06 08:53 UTC, emile-bex commented on src/opportunities/opportunities.controller.ts
> +
Pourquoi cette condition ?
Le pipe avec son DTO devrait s'occuper de ça normalement

2023-02-06 08:53 UTC, emile-bex commented on src/opportunities/opportunities.controller.ts
> +    }
Pareil, les pipes sont censées gérer ça (si une des valeurs n'est pas renseigné, le `ParseUUIDPipe` renvoie une erreur).

Tu peux rajouter le pipe `ParseStringPipe` pour le paramètre `type`

2023-02-06 08:53 UTC, emile-bex commented on tests/opportunities/opportunities.e2e-spec.ts
> +        });
Il faudrait rajouter des tests :
- 400 pour tester si on oublie des valeurs obligatoires
- 201 si on enlève des valeurs optionnels (`coachNotification` par exemple)
- 403 si un candidat essaye de contacter un recruteur sur une offre ou il n'est pas associé
- 403 si un coach essaye de contacter un recruteur sur une offre ou son candidat n'est pas associé
- 404 si un candidat essaye de contacter un recruteur sur une offre qui n'existe pas
- 404 si un coach essaye de contacter un recruteur sur une offre qui n'existe pas

2023-02-06 08:53 UTC, emile-bex commented on tests/opportunities/opportunities.e2e-spec.ts
> +        it('Should return 200 if coach uses the route', async () => {
```suggestion
        it('Should return 201 if coach uses the route', async () => {
```

2023-02-06 08:53 UTC, emile-bex commented on tests/opportunities/opportunities.e2e-spec.ts
> +        it('Should return 200 if candidates uses the route', async () => {
```suggestion
        it('Should return 201 if candidates uses the route', async () => {
```

2023-02-06 09:12 UTC, PaulEntourage commented on src/mails/mails.service.ts
> +    })
bien vu !

2023-02-06 09:13 UTC, PaulEntourage commented on src/opportunities/opportunities.controller.ts
> +
Yes t'as raison.

2023-02-06 09:13 UTC, PaulEntourage commented on src/opportunities/opportunities.controller.ts
> +    }
OK

2023-02-06 09:13 UTC, PaulEntourage commented on tests/opportunities/opportunities.e2e-spec.ts
> +        it('Should return 200 if coach uses the route', async () => {
Ok

2023-02-06 09:14 UTC, PaulEntourage commented on tests/opportunities/opportunities.e2e-spec.ts
> +        it('Should return 200 if candidates uses the route', async () => {
Ok

2023-02-07 08:50 UTC, emile-bex approved these changes

2023-02-07 08:50 UTC, merged