[EN-6287] feat(cv): cv - experience et formation
ReseauEntourage/entourage-job-back pull request #94
Opened 2023-07-27 14:19 UTC by PaulEntourage

2023-08-30 09:33 UTC, emile-bex requested changes

2023-08-30 09:33 UTC, emile-bex commented on src/cvs/cvs.controller.ts
> +
Je mettrais ces valeurs dans des constantes 😉

2023-08-30 09:33 UTC, emile-bex commented on src/cvs/cvs.service.ts
> +    return await this.findAndCacheOneByUrl(url);
Pourquoi tu as enlevé ça ? C'est important de le garder, ça nous permet de récupérer la version caché dans CV dans REDIS pour améliorer les performances (surtout si on a beaucoup de traffic)

2023-08-30 09:33 UTC, emile-bex commented on tests/cvs/cv.factory.ts
> +                  }
Tu peux pas factoriser avec le `
                  if (
                    injectedModel.name === 'Experience')` d'au dessus ?

2023-09-01 13:56 UTC, PaulEntourage commented on src/cvs/cvs.controller.ts
> +
OK

2023-09-01 13:57 UTC, PaulEntourage commented on src/cvs/cvs.service.ts
> +    return await this.findAndCacheOneByUrl(url);
Erreur, j'ai déjà corrigé :)

2023-09-01 14:21 UTC, PaulEntourage commented on tests/cvs/cv.factory.ts
> +                  }
Si totalement :)

2023-09-04 08:28 UTC, merged