feat(gen-pdf): generation pdf sur lambda
ReseauEntourage/entourage-job-back pull request #99
Opened 2023-09-20 13:24 UTC by PaulEntourage

2023-09-20 14:21 UTC, emile-bex requested changes

2023-09-20 14:21 UTC, emile-bex commented on src/cvs/cvs.service.ts
> +    /*paths: string[],*/ fileName: string
Si tu change ça ça veut dire que c'est dans la lambda qu'on crée les paths ? Pourquoi on a besoin de modifier ça ?

2023-09-20 14:21 UTC, emile-bex commented on src/cvs/cvs.controller.ts
> +        `${firstName}_${lastName}`
Pour le `fileName` il faudrait reprendre ce qu'il y a dans la fonction `getPDFPaths` : `${firstName}_${lastName}_${candidateId.substring(0, 8)}.pdf` avec le remplacement des single quote (et enlever la partie `-page1.pdf` et `-page2.pdf` s'il y en a pas besoin). Il faudra garder ce format pour les noms des PDFs.

2023-10-05 10:42 UTC, PaulEntourage commented on src/cvs/cvs.controller.ts
> +        `${firstName}_${lastName}`
Ca c'est sur la Lambda ;)

2023-10-05 10:43 UTC, PaulEntourage commented on src/cvs/cvs.service.ts
> +    /*paths: string[],*/ fileName: string
Oui c'est ce qu'on a vu ensemble, le getPDF Paths se fait sur la lambda, ca clarifie la requête

2023-10-05 13:45 UTC, emile-bex approved these changes

2023-10-17 08:52 UTC, merged